site:
    title: Posts
    description: "Talks about Symfony2, git and other developer stuff"
    author_name:  Loïc Chardonnet
    author_email: loic.chardonnet@gmail.com
    author_url: http://gnugat.github.io
    url_absolute: http://gnugat.github.io
    disqus_shortname: gnugatgithubio

engine:
    themes:
        - "%dir%/vendor/carew/theme-bootstrap"
