site:
    title: Technical Blog
    description: "Technical articles about Symfony and TDD"
    author_name:  Loïc Faugeron
    author_email: faugeron.loic+blog@gmail.com
    author_url: http://gnugat.github.io
    url_absolute: http://gnugat.github.io
    disqus_shortname: gnugatgithubio

engine:
    extensions:
        - Gnugat\CarewNext\NextExtension
